(() => {
  const VERSION='25';
  let data=null, button=null, panel=null;
  const qs=(s,r=document)=>r.querySelector(s);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function ensureCss(){if(qs('#nb-bio-css'))return;const s=document.createElement('style');s.id='nb-bio-css';s.textContent=`#nb-bio-panel{position:absolute;z-index:8;left:18px;top:118px;width:min(430px,calc(100% - 36px));max-height:62vh;overflow:auto;padding:14px;border:1px solid #ffffff3a;border-radius:16px;background:#07110dee;color:#fff;box-shadow:0 18px 55px #0008;backdrop-filter:blur(10px);font-size:.76rem;line-height:1.45}#nb-bio-panel[hidden]{display:none}#nb-bio-panel h3{margin:.1rem 2.3rem .45rem 0;font-size:1rem}#nb-bio-panel h4{margin:.9rem 0 .35rem;font-size:.82rem}#nb-bio-panel p{margin:.3rem 0;color:#dce5dc}#nb-bio-panel ul{margin:.25rem 0 .5rem;padding-left:1.15rem;color:#dce5dc}#nb-bio-panel li{margin:.18rem 0}#nb-bio-panel .bio-tag{display:inline-block;margin:.15rem .2rem .15rem 0;padding:.2rem .45rem;border:1px solid #ffffff2f;border-radius:999px;background:#ffffff10;color:#e9f0e9;font-size:.68rem}#nb-bio-panel .bio-note{padding:.55rem .65rem;border-radius:10px;background:#ffffff0d;color:#cbd8cd}#nb-bio-panel button{position:absolute;right:8px;top:8px;min-width:32px;min-height:32px;border:0;border-radius:999px;background:#ffffff14;color:#fff;cursor:pointer}@media(max-width:700px){#nb-bio-panel{left:10px;right:10px;top:142px;width:auto;max-height:52vh}}`;document.head.appendChild(s);}
  function render(){if(!panel||!data)return;const habitats=(data.habitats||[]).map(h=>`<li><b>${esc(h.label)}</b><br><span class="bio-tag">${esc(h.status)}</span> ${esc(h.risks?.join(' · ')||'')}</li>`).join('');const surveys=(data.survey_targets||[]).map(x=>`<span class="bio-tag">${esc(x)}</span>`).join('');const species=(data.species_examples||[]).map(x=>`<li><b>${esc(x.common_name)}</b> <i>${esc(x.scientific_name)}</i><br>${esc(x.status)}</li>`).join('');panel.innerHTML=`<button type="button" aria-label="Close biodiversity panel">×</button><h3>Biodiversity evidence lens</h3><p class="bio-note">${esc(data.warning)}</p><h4>Authority/source-supported habitat context</h4><ul>${habitats}</ul><h4>Targeted survey groups</h4><p>${surveys}</p><h4>Source-supported species example</h4><ul>${species}</ul><h4>What we will quantify next</h4><p>Habitat loss, connectivity/fragmentation, disturbance, riparian risk and residual effect after mitigation — only when verified geometry and current survey evidence support the precision.</p>`;panel.querySelector('button').addEventListener('click',()=>{panel.hidden=true;button?.setAttribute('aria-pressed','false');});}
  function ensurePanel(){if(panel?.isConnected)return;const host=qs('#immersive-experience');if(!host)return;panel=document.createElement('aside');panel.id='nb-bio-panel';panel.hidden=true;host.appendChild(panel);render();}
  function ensureButton(){const toolbar=qs('.hud-actions');if(!toolbar||button?.isConnected)return;button=document.createElement('button');button.type='button';button.dataset.biodiversity='';button.textContent='Biodiversity';button.setAttribute('aria-pressed','false');button.setAttribute('aria-label','Show biodiversity evidence and ecological impact context');toolbar.insertBefore(button,toolbar.querySelector('[data-exit]')||null);button.addEventListener('click',()=>{ensurePanel();const next=panel.hidden;panel.hidden=!next;button.setAttribute('aria-pressed',next?'true':'false');});}
  async function load(){try{const r=await fetch('data/biodiversity-context.json',{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);data=await r.json();ensureCss();ensureButton();ensurePanel();window.NorthBarnesBiodiversity={version:VERSION,state:()=>({loaded:true,status:data.status})};}catch(e){console.warn('Biodiversity evidence layer unavailable',e);window.NorthBarnesBiodiversity={version:VERSION,state:()=>({loaded:false,error:String(e.message||e)})};}}
  load();
  const mo=new MutationObserver(()=>{ensureButton();ensurePanel();});mo.observe(document.documentElement,{subtree:true,childList:true});
})();
