(()=>{
const V='31.0';
const YEARS=[0,5,10,15,20,25];
const DWELLINGS={0:0,5:700,10:1400,15:2100,20:2650,25:3000};
const LABEL={0:'Existing landscape',5:'Enabling works + first neighbourhoods',10:'Expanding road-led settlement',15:'Mid-build settlement',20:'Later neighbourhoods + facilities',25:'Full analytical scenario'};
let host=null,panel=null,button=null,slider=null,playButton=null,yearLabel=null,homesLabel=null,phaseLabel=null,playing=false,token=0,watch=null;
const q=(s,r=document)=>r.querySelector(s),reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches,sleep=ms=>new Promise(r=>setTimeout(r,ms));
function status(t){const e=q('[data-exp-status]');if(e)e.textContent=t;}
function css(){if(q('#nb-v31-css'))return;const s=document.createElement('style');s.id='nb-v31-css';s.textContent=`#nb-v31-panel{position:absolute;z-index:19;left:50%;bottom:18px;transform:translateX(-50%);width:min(860px,calc(100% - 24px));padding:12px 14px;border:1px solid #ffffff3f;border-radius:16px;background:#07110df0;color:#fff;backdrop-filter:blur(13px);box-shadow:0 15px 50px #0007;font:13px/1.35 system-ui,sans-serif}#nb-v31-panel[hidden]{display:none}.nb31-top{display:flex;gap:10px;align-items:flex-start;justify-content:space-between}.nb31-top strong{display:block;color:#f3d37a;font-size:.78rem;letter-spacing:.08em;text-transform:uppercase}.nb31-title{font-size:1.04rem;font-weight:800;margin-top:2px}.nb31-metric{text-align:right;white-space:nowrap}.nb31-metric b{font-size:1.05rem}.nb31-controls{display:grid;grid-template-columns:auto 1fr auto;gap:10px;align-items:center;margin-top:10px}.nb31-controls button{min-height:40px;padding:7px 12px;border-radius:999px;border:1px solid #ffffff45;background:#ffffff10;color:#fff;font:inherit;font-weight:800}.nb31-controls button[data-primary]{background:#f3d37a;color:#142218;border-color:#f3d37a}.nb31-controls input{width:100%;accent-color:#f3d37a}.nb31-scale{display:flex;justify-content:space-between;color:#c9d5cc;font-size:.68rem;margin:5px 2px 0}.nb31-note{margin:7px 0 0;color:#c9d5cc;font-size:.72rem}.nb-v31-active #nb-v30-summary{display:none!important}@media(max-width:700px){#nb-v31-panel{bottom:7px;width:calc(100% - 14px);padding:10px;border-radius:13px;font-size:12px}.nb31-controls{grid-template-columns:auto 1fr;gap:7px}.nb31-controls button[data-close]{grid-column:1/-1}.nb31-metric{font-size:.72rem}.nb31-note{display:none}}`;document.head.appendChild(s)}
function ensure(){css();host=q('#immersive-experience');if(!host)return;const bar=q('.hud-actions');if(bar&&!button?.isConnected){button=document.createElement('button');button.type='button';button.dataset.cinematicV31='';button.textContent='Build animation';button.title='Animate the illustrative 25-year settlement scenario';const p=bar.querySelector('[data-presentation]');bar.insertBefore(button,p?p.nextSibling:bar.firstChild);button.addEventListener('click',()=>panel?.hidden?open():close())}if(!panel?.isConnected){panel=document.createElement('section');panel.id='nb-v31-panel';panel.hidden=true;panel.setAttribute('aria-label','North Barnes animated build scenario');panel.innerHTML='<div class="nb31-top"><div><strong>v31 cinematic build sequence</strong><div class="nb31-title" data-v31-phase></div></div><div class="nb31-metric"><b data-v31-homes>0</b><br><span>illustrative dwellings</span></div></div><div class="nb31-controls"><button type="button" data-primary data-v31-play>Play</button><input type="range" min="0" max="5" step="1" value="0" data-v31-range aria-label="Scenario year"><button type="button" data-close data-v31-close>Close</button></div><div class="nb31-scale"><span>Today</span><span>5</span><span>10</span><span>15</span><span>20</span><span>25 yrs</span></div><p class="nb31-note">Illustrative analytical phasing, not an official construction programme or masterplan.</p>';host.appendChild(panel);slider=q('[data-v31-range]',panel);playButton=q('[data-v31-play]',panel);yearLabel=q('[data-v31-phase]',panel);homesLabel=q('[data-v31-homes]',panel);phaseLabel=yearLabel;slider.addEventListener('input',()=>{stop();setIndex(+slider.value,true)});playButton.addEventListener('click',()=>playing?stop():play());q('[data-v31-close]',panel).addEventListener('click',close)}}
function camera(year){const map=window.__northBarnesMap;if(!map)return;const cams={0:{center:[-0.049,50.9335],zoom:11.25,pitch:48,bearing:-12},5:{center:[-0.0505,50.9315],zoom:13.35,pitch:58,bearing:42},10:{center:[-0.048,50.933],zoom:13.75,pitch:62,bearing:105},15:{center:[-0.0478,50.9342],zoom:14.05,pitch:65,bearing:170},20:{center:[-0.0502,50.9345],zoom:14.18,pitch:65,bearing:235},25:{center:[-0.049,50.9335],zoom:13.95,pitch:61,bearing:300}};const c=cams[year]||cams[25];try{map.flyTo({...c,duration:reduced()?0:2100,curve:1.2,speed:.82,essential:!reduced()})}catch(_){}}
function updateUi(year){if(!panel)return;phaseLabel.textContent=(year?`Year ${year} · `:'Today · ')+LABEL[year];homesLabel.textContent=DWELLINGS[year].toLocaleString('en-GB');slider.value=String(YEARS.indexOf(year));playButton.textContent=playing?'Pause':'Play'}
async function setYear(year,move=false){const p=window.NorthBarnesProposal;if(year===0){p?.setVisible?.(false,false)}else{p?.setVisible?.(true,false);p?.setYear?.(year)}updateUi(year);if(move)camera(year);status(`v31 build animation · ${LABEL[year]} · ${DWELLINGS[year].toLocaleString('en-GB')} dwellings represented`);return year}
function setIndex(i,move=false){i=Math.max(0,Math.min(YEARS.length-1,i));return setYear(YEARS[i],move)}
function open(){ensure();if(!panel)return;panel.hidden=false;document.documentElement.classList.add('nb-v31-active');playing=false;updateUi(YEARS[+slider.value]||0);setIndex(+slider.value,true)}
function close(){stop();if(panel)panel.hidden=true;document.documentElement.classList.remove('nb-v31-active');status('Build animation closed · interactive inspection available')}
function stop(){token++;playing=false;if(playButton)playButton.textContent='Play';try{window.__northBarnesMap?.stop?.()}catch(_){}}
async function play(){if(playing)return;playing=true;const t=++token;let start=Math.max(0,+slider.value);if(start>=YEARS.length-1)start=0;for(let i=start;i<YEARS.length;i++){if(t!==token)return;slider.value=String(i);await setIndex(i,true);updateUi(YEARS[i]);await sleep(reduced()?450:2800)}if(t===token){playing=false;updateUi(25);status('v31 cinematic sequence complete · Year 25 · exactly 3,000 dwellings represented')}}
function discover(){ensure();if(!watch)watch=setInterval(ensure,700)}
window.NorthBarnesCinematicV31={version:V,open,close,play,stop,setYear,state:()=>({open:!!panel&&!panel.hidden,playing,year:YEARS[+(slider?.value||0)]})};
discover();addEventListener('pagehide',()=>{if(watch)clearInterval(watch);stop()},{once:true});
})();
