(()=>{
const V='33.0',CFG='data/google-map-tiles-config.json',C={lon:-0.049,lat:50.9335,height:1450,heading:18,pitch:-48};
let cfg=null,viewer=null,container=null,button=null,mode='map',loading=false,watch=null,configChecked=false;
const q=(s,r=document)=>r.querySelector(s),status=t=>{const e=q('[data-exp-status]');if(e)e.textContent=t;};
function css(){if(q('#nb-google3d-css'))return;const s=document.createElement('style');s.id='nb-google3d-css';s.textContent='#nb-google3d{position:absolute;inset:0;z-index:2;background:#0b1510}#nb-google3d[hidden]{display:none}#nb-google3d .cesium-viewer-bottom{bottom:5px}.nb-google3d-active #nb3d>.maplibregl-map{visibility:hidden}.nb-google3d-active [data-context-mode]{opacity:.55}';document.head.appendChild(s)}
function loadCss(u){if([...document.styleSheets].some(x=>x.href===u))return;const l=document.createElement('link');l.rel='stylesheet';l.href=u;document.head.appendChild(l)}
function script(u){return new Promise((res,rej)=>{if(window.Cesium)return res();const s=document.createElement('script');s.src=u;s.async=true;s.onload=res;s.onerror=()=>rej(Error('Cesium CDN unavailable'));document.head.appendChild(s)})}
async function config(){if(configChecked)return cfg;configChecked=true;try{const r=await fetch(CFG,{cache:'no-store'});if(!r.ok)throw Error(String(r.status));const d=await r.json();if(d?.enabled!==true||!d?.api_key||d?.provider!=='Google Photorealistic 3D Tiles')throw Error('disabled or invalid');cfg=d;return d}catch(_){cfg=null;return null}}
function ensureUI(){css();const host=q('#nb3d');if(host&&!container){container=document.createElement('div');container.id='nb-google3d';container.hidden=true;host.appendChild(container)}const bar=q('.hud-actions');if(bar&&!button?.isConnected){button=document.createElement('button');button.type='button';button.dataset.google3d='';button.textContent='Google 3D';button.title='Switch to Google Photorealistic 3D landscape context';const context=bar.querySelector('[data-context-mode]');bar.insertBefore(button,context?context.nextSibling:null);button.onclick=()=>setMode(mode==='google'?'map':'google')}}
async function init(){if(viewer)return true;if(loading)return false;loading=true;ensureUI();const c=await config();if(!c){loading=false;button&&(button.hidden=true);status('Google Photorealistic 3D is not configured for this release');return false}try{loadCss('https://cdn.jsdelivr.net/npm/cesium@1.133.0/Build/Cesium/Widgets/widgets.css');await script('https://cdn.jsdelivr.net/npm/cesium@1.133.0/Build/Cesium/Cesium.js');viewer=new Cesium.Viewer(container,{globe:false,baseLayerPicker:false,geocoder:false,homeButton:false,sceneModePicker:false,navigationHelpButton:false,animation:false,timeline:false,fullscreenButton:false,selectionIndicator:false,infoBox:false,requestRenderMode:true});const tileset=viewer.scene.primitives.add(new Cesium.Cesium3DTileset({url:`https://tile.googleapis.com/v1/3dtiles/root.json?key=${encodeURIComponent(c.api_key)}`,showCreditsOnScreen:true,maximumScreenSpaceError:window.innerWidth<700?24:12}));let tilesetReady=true;try{if(tileset.readyPromise)await tileset.readyPromise}catch(_){tilesetReady=false}if(!tilesetReady){try{viewer.destroy()}catch(_){}viewer=null;loading=false;status('Google Photorealistic 3D unavailable · OS/OSM context retained');return false}viewer.camera.setView({destination:Cesium.Cartesian3.fromDegrees(C.lon,C.lat,C.height),orientation:{heading:Cesium.Math.toRadians(C.heading),pitch:Cesium.Math.toRadians(C.pitch),roll:0}});viewer.scene.requestRender();loading=false;return true}catch(e){console.error('Google 3D init failed',e);loading=false;status('Google Photorealistic 3D unavailable · OS/OSM context retained');return false}}
async function setMode(next){ensureUI();if(next==='google'){if(!(await init()))return false;mode='google';container.hidden=false;document.documentElement.classList.add('nb-google3d-active');button&&(button.textContent='Map context');status('Google Photorealistic 3D landscape · live presentation context · proposal geometry remains illustrative');viewer.resize();viewer.scene.requestRender();return true}mode='map';container&&(container.hidden=true);document.documentElement.classList.remove('nb-google3d-active');button&&(button.textContent='Google 3D');status('Map context · proposal geometry illustrative');return true}
async function flyTo({center=[C.lon,C.lat],height=900,heading=0,pitch=-48,duration=3}={}){if(mode!=='google'&&!(await setMode('google')))return false;const [lon,lat]=center;viewer.camera.flyTo({destination:Cesium.Cartesian3.fromDegrees(lon,lat,height),orientation:{heading:Cesium.Math.toRadians(heading),pitch:Cesium.Math.toRadians(pitch),roll:0},duration:matchMedia('(prefers-reduced-motion: reduce)').matches?0:duration});return true}
function discover(){ensureUI();if(!watch)watch=setInterval(ensureUI,900);config().then(c=>{if(!c&&button)button.hidden=true})}
window.NorthBarnesGoogle3D={version:V,setMode,flyTo,state:()=>({mode,ready:!!viewer,configured:!!cfg,configChecked})};discover();addEventListener('pagehide',()=>{if(watch)clearInterval(watch);try{viewer?.destroy?.()}catch(_){}},{once:true});
})();
