(()=>{
const V='29.3',C=[-0.049,50.9335];
let map=null,button=null,panel=null,index=0,playing=false,token=0,watch=null;
const q=(s,r=document)=>r.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms)),reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
const scenes=[
 {k:'existing',title:'1 · The landscape today',body:'Start with the existing rural landscape and terrain before any illustrative proposal geometry is shown.',proposal:false,cam:{center:C,zoom:11.25,pitch:48,bearing:-12,duration:2600}},
 {k:'approach',title:'2 · North Barnes in its wider setting',body:'Move from the Downs and surrounding settlements toward the Site 11EC study area. Camera anchors remain illustrative until verified GIS is locked.',proposal:false,cam:{center:[-0.049,50.9335],zoom:12.55,pitch:55,bearing:18,duration:3000}},
 {k:'year5',title:'3 · Early enabling and Year 5',body:'Illustrative scenario: first neighbourhoods, roads and enabling infrastructure. 700 dwelling units are represented at this stage.',proposal:true,year:5,cam:{center:[-0.0505,50.9315],zoom:13.45,pitch:58,bearing:42,duration:3200}},
 {k:'year10',title:'4 · Expansion through Year 10',body:'Illustrative settlement growth reaches 1,400 dwelling units, with the internal movement network and open-space structure becoming legible.',proposal:true,year:10,cam:{center:[-0.048,50.933],zoom:13.85,pitch:62,bearing:105,duration:3200}},
 {k:'year15',title:'5 · Mid-build settlement',body:'By the analytical Year 15 scenario, 2,100 dwelling units are represented alongside parks, paths and community infrastructure.',proposal:true,year:15,cam:{center:[-0.0478,50.9342],zoom:14.25,pitch:66,bearing:170,duration:3300}},
 {k:'year20',title:'6 · Later neighbourhoods and facilities',body:'The Year 20 scenario represents 2,650 dwelling units. Facilities, employment uses and green infrastructure remain illustrative unless source-derived.',proposal:true,year:20,cam:{center:[-0.0502,50.9345],zoom:14.35,pitch:66,bearing:235,duration:3300}},
 {k:'year25',title:'7 · Full 3,000-dwelling scenario',body:'Year 25 shows the full analytical scale: exactly 3,000 dwelling units represented across a mixed settlement morphology.',proposal:true,year:25,cam:{center:C,zoom:14.1,pitch:62,bearing:300,duration:3400}},
 {k:'close',title:'8 · Street-edge inspection',body:'Zoom in to inspect the illustrative relationship between buildings, local streets, parks, drainage and community uses.',proposal:true,year:25,cam:{center:[-0.0481,50.9329],zoom:15.35,pitch:72,bearing:24,duration:3500}},
 {k:'final',title:'9 · The scale in context',body:'Return to the wider landscape to judge the overall scale. This is an evidence-led illustrative scenario, not an official masterplan.',proposal:true,year:25,cam:{center:C,zoom:13.45,pitch:54,bearing:-18,duration:3300}}
];
function css(){if(q('#nb-presentation-css'))return;const s=document.createElement('style');s.id='nb-presentation-css';s.textContent=`#nb-presentation-panel{position:absolute;z-index:12;left:50%;bottom:18px;transform:translateX(-50%);width:min(860px,calc(100% - 24px));padding:14px 16px;border:1px solid #ffffff45;border-radius:18px;background:#07110ded;color:#fff;box-shadow:0 18px 70px #0009;backdrop-filter:blur(14px);font:15px/1.38 system-ui,sans-serif}#nb-presentation-panel[hidden]{display:none}#nb-presentation-panel h2{margin:0 0 5px;font-size:clamp(1.05rem,2vw,1.35rem)}#nb-presentation-panel p{margin:0;color:#dce6dd}.nbp-row{display:flex;align-items:center;gap:8px;margin-top:11px;flex-wrap:wrap}.nbp-row button{min-height:42px;padding:8px 13px;border-radius:999px;border:1px solid #ffffff45;background:#ffffff12;color:#fff;font:inherit;font-weight:800}.nbp-row button[data-primary]{background:#f3d37a;color:#142218;border-color:#f3d37a}.nbp-progress{height:4px;flex:1 1 170px;background:#ffffff20;border-radius:99px;overflow:hidden}.nbp-progress>i{display:block;height:100%;background:#f3d37a;width:0;transition:width .35s}.nbp-count{font-size:.78rem;color:#c8d3ca}.nb-presentation-active .hud-actions{opacity:.16;transition:opacity .25s}.nb-presentation-active .hud-actions:hover,.nb-presentation-active .hud-actions:focus-within{opacity:1}@media(max-width:700px){#nb-presentation-panel{bottom:8px;padding:11px 12px;border-radius:14px;font-size:13px}.nbp-row button{min-height:40px;padding:7px 11px}}`;document.head.appendChild(s)}
function ensureUI(){css();const host=q('#immersive-experience');if(!host)return;const bar=q('.hud-actions');if(bar&&!button?.isConnected){button=document.createElement('button');button.type='button';button.dataset.presentation='';button.textContent='Presentation';button.title='Run the client presentation story';bar.insertBefore(button,bar.firstChild);button.addEventListener('click',()=>panel?.hidden?open():close())}if(!panel?.isConnected){panel=document.createElement('section');panel.id='nb-presentation-panel';panel.hidden=true;panel.setAttribute('aria-live','polite');panel.innerHTML='<h2 data-nbp-title></h2><p data-nbp-body></p><div class="nbp-row"><button type="button" data-nbp-prev>Back</button><button type="button" data-primary data-nbp-play>Play</button><button type="button" data-nbp-next>Next</button><div class="nbp-progress" aria-hidden="true"><i></i></div><span class="nbp-count"></span><button type="button" data-nbp-exit>Exit</button></div>';host.appendChild(panel);q('[data-nbp-prev]',panel).onclick=()=>go(Math.max(0,index-1));q('[data-nbp-next]',panel).onclick=()=>go(Math.min(scenes.length-1,index+1));q('[data-nbp-play]',panel).onclick=()=>playing?stop():play();q('[data-nbp-exit]',panel).onclick=close}}
function status(t){const e=q('[data-exp-status]');if(e)e.textContent=t}
function proposal(on,year){window.NorthBarnesProposal?.setVisible?.(!!on,false);if(on&&year)window.NorthBarnesProposal?.setYear?.(year)}
async function move(cam){if(!map)return;const d=reduced()?0:(cam.duration||2800);await new Promise(res=>{let done=false;const fin=()=>{if(done)return;done=true;clearTimeout(to);res()},to=setTimeout(fin,Math.max(600,d+700));map.once?.('moveend',fin);map.flyTo?.({...cam,duration:d,curve:1.28,speed:.78,essential:!reduced()})})}
function render(){ensureUI();const s=scenes[index];q('[data-nbp-title]',panel).textContent=s.title;q('[data-nbp-body]',panel).textContent=s.body;q('.nbp-count',panel).textContent=`${index+1}/${scenes.length}`;q('.nbp-progress i',panel).style.width=`${((index+1)/scenes.length)*100}%`;q('[data-nbp-prev]',panel).disabled=index===0;q('[data-nbp-next]',panel).disabled=index===scenes.length-1;q('[data-nbp-play]',panel).textContent=playing?'Pause':'Play'}
async function go(i,expected=null){if(!map)return;index=Math.max(0,Math.min(scenes.length-1,i));render();const s=scenes[index];proposal(s.proposal,s.year);status(`Presentation · ${s.title}`);await sleep(120);if(expected!==null&&expected!==token)return;await move(s.cam)}
function open(){ensureUI();panel.hidden=false;document.documentElement.classList.add('nb-presentation-active');index=0;render();go(0)}
function close(){stop();if(panel)panel.hidden=true;document.documentElement.classList.remove('nb-presentation-active');status('Presentation closed · interactive inspection available')}
function stop(){token++;playing=false;render();try{map?.stop?.()}catch(_){}}
async function play(){if(playing)return;playing=true;const t=++token;render();for(let i=index;i<scenes.length;i++){if(t!==token)return;await go(i,t);if(t!==token)return;await sleep(reduced()?250:1450)}if(t===token){playing=false;render();status('Presentation complete · Year 25 · 3,000 dwelling units represented')}}
function discover(){ensureUI();const m=window.__northBarnesMap;if(m&&m!==map)map=m;if(!watch)watch=setInterval(()=>{ensureUI();const n=window.__northBarnesMap;if(n&&n!==map)map=n},700)}
document.addEventListener('keydown',e=>{if(panel?.hidden)return;if(e.key==='Escape'){e.preventDefault();close()}else if(e.key==='ArrowRight'){e.preventDefault();stop();go(index+1)}else if(e.key==='ArrowLeft'){e.preventDefault();stop();go(index-1)}else if(e.key===' '){e.preventDefault();playing?stop():play()}});
window.NorthBarnesPresentation={version:V,open,close,play,stop,go,state:()=>({open:!!panel&&!panel.hidden,index,playing,scene:scenes[index]?.k})};discover();addEventListener('pagehide',()=>{if(watch)clearInterval(watch);stop()},{once:true});
})();
