(()=>{
const V='29.4',C=[-0.049,50.9335],AUTO=new URLSearchParams(location.search).get('presentation')==='1';
let map=null,button=null,panel=null,index=0,playing=false,token=0,watch=null,autoOpened=false;
const q=(s,r=document)=>r.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms)),reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
const scenes=[
 {k:'existing',title:'1 · The landscape today',body:'Existing rural landscape and terrain, before any illustrative proposal geometry is shown.',proposal:false,cam:{center:C,zoom:11.25,pitch:48,bearing:-12,duration:2600}},
 {k:'approach',title:'2 · North Barnes in its wider setting',body:'Move from the Downs and surrounding settlements toward the Site 11EC study area.',proposal:false,cam:{center:[-0.049,50.9335],zoom:12.55,pitch:55,bearing:18,duration:3000}},
 {k:'year5',title:'3 · Early enabling and Year 5',body:'Illustrative first neighbourhoods, roads and enabling infrastructure · 700 dwelling units.',proposal:true,year:5,cam:{center:[-0.0505,50.9315],zoom:13.45,pitch:58,bearing:42,duration:3200}},
 {k:'year10',title:'4 · Expansion through Year 10',body:'Illustrative growth to 1,400 dwelling units as the movement and open-space structure develops.',proposal:true,year:10,cam:{center:[-0.048,50.933],zoom:13.85,pitch:62,bearing:105,duration:3200}},
 {k:'year15',title:'5 · Mid-build settlement',body:'Year 15 analytical scenario · 2,100 dwelling units with parks, paths and community infrastructure.',proposal:true,year:15,cam:{center:[-0.0478,50.9342],zoom:14.25,pitch:66,bearing:170,duration:3300}},
 {k:'year20',title:'6 · Later neighbourhoods and facilities',body:'Year 20 analytical scenario · 2,650 dwelling units. Facilities and green infrastructure remain illustrative unless source-derived.',proposal:true,year:20,cam:{center:[-0.0502,50.9345],zoom:14.35,pitch:66,bearing:235,duration:3300}},
 {k:'year25',title:'7 · Full 3,000-dwelling scenario',body:'Year 25 shows the full analytical scale: exactly 3,000 dwelling units represented.',proposal:true,year:25,cam:{center:C,zoom:14.1,pitch:62,bearing:300,duration:3400}},
 {k:'close',title:'8 · Street-edge inspection',body:'Inspect the illustrative relationship between buildings, local streets, parks, drainage and community uses.',proposal:true,year:25,cam:{center:[-0.0481,50.9329],zoom:15.35,pitch:72,bearing:24,duration:3500}},
 {k:'final',title:'9 · The scale in context',body:'Return to the wider landscape to judge overall scale. Illustrative scenario · not an official masterplan.',proposal:true,year:25,cam:{center:C,zoom:13.45,pitch:54,bearing:-18,duration:3300}}
];
function css(){if(q('#nb-presentation-css'))return;const s=document.createElement('style');s.id='nb-presentation-css';s.textContent=`#nb-presentation-panel{position:absolute;z-index:20;left:50%;bottom:18px;transform:translateX(-50%);width:min(780px,calc(100% - 24px));padding:13px 15px;border:1px solid #ffffff3d;border-radius:16px;background:#07110df2;color:#fff;box-shadow:0 14px 48px #0008;backdrop-filter:blur(12px);font:14px/1.34 system-ui,sans-serif}#nb-presentation-panel[hidden]{display:none}#nb-presentation-panel h2{margin:0 0 4px;font-size:clamp(1rem,2vw,1.26rem)}#nb-presentation-panel p{margin:0;color:#dce6dd}.nbp-row{display:flex;align-items:center;gap:7px;margin-top:9px;flex-wrap:nowrap}.nbp-row button{min-height:38px;padding:7px 12px;border-radius:999px;border:1px solid #ffffff42;background:#ffffff10;color:#fff;font:inherit;font-weight:800}.nbp-row button[data-primary]{background:#f3d37a;color:#142218;border-color:#f3d37a}.nbp-progress{height:4px;flex:1 1 140px;background:#ffffff1f;border-radius:99px;overflow:hidden}.nbp-progress>i{display:block;height:100%;background:#f3d37a;width:0;transition:width .35s}.nbp-count{font-size:.75rem;color:#c8d3ca;white-space:nowrap}.nb-presentation-active .hud-actions,.nb-presentation-active #nb-v28-summary,.nb-presentation-active .maplibregl-ctrl-top-right,.nb-presentation-active .mapboxgl-ctrl-top-right{display:none!important}.nb-presentation-active #immersive-experience{cursor:default}@media(max-width:700px){#nb-presentation-panel{bottom:7px;width:calc(100% - 14px);padding:9px 10px;border-radius:13px;font-size:12px;line-height:1.25}#nb-presentation-panel h2{font-size:.98rem;margin-bottom:3px}#nb-presentation-panel p{display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.nbp-row{gap:5px;margin-top:7px}.nbp-row button{min-height:34px;padding:5px 9px;font-size:12px}.nbp-progress{flex-basis:72px}.nbp-count{font-size:.68rem}}`;document.head.appendChild(s)}
function ensureUI(){css();const host=q('#immersive-experience');if(!host)return;const bar=q('.hud-actions');if(bar&&!button?.isConnected){button=document.createElement('button');button.type='button';button.dataset.presentation='';button.textContent='Presentation';button.title='Run the client presentation story';bar.insertBefore(button,bar.firstChild);button.addEventListener('click',()=>panel?.hidden?open():close())}if(!panel?.isConnected){panel=document.createElement('section');panel.id='nb-presentation-panel';panel.hidden=true;panel.setAttribute('aria-live','polite');panel.innerHTML='<h2 data-nbp-title></h2><p data-nbp-body></p><div class="nbp-row"><button type="button" data-nbp-prev>Back</button><button type="button" data-primary data-nbp-play>Play</button><button type="button" data-nbp-next>Next</button><div class="nbp-progress" aria-hidden="true"><i></i></div><span class="nbp-count"></span><button type="button" data-nbp-exit>Exit</button></div>';host.appendChild(panel);q('[data-nbp-prev]',panel).onclick=()=>{stop();go(index-1)};q('[data-nbp-next]',panel).onclick=()=>{stop();go(index+1)};q('[data-nbp-play]',panel).onclick=()=>playing?stop():play();q('[data-nbp-exit]',panel).onclick=close}}
function status(t){const e=q('[data-exp-status]');if(e)e.textContent=t}
function proposal(on,year){window.NorthBarnesProposal?.setVisible?.(!!on,false);if(on&&year)window.NorthBarnesProposal?.setYear?.(year)}
async function move(cam){if(!map)return;const d=reduced()?0:(cam.duration||2800);await new Promise(res=>{let done=false;const fin=()=>{if(done)return;done=true;clearTimeout(to);res()},to=setTimeout(fin,Math.max(600,d+700));map.once?.('moveend',fin);map.flyTo?.({...cam,duration:d,curve:1.28,speed:.78,essential:!reduced()})})}
function render(){ensureUI();if(!panel)return;const s=scenes[index];q('[data-nbp-title]',panel).textContent=s.title;q('[data-nbp-body]',panel).textContent=s.body;q('.nbp-count',panel).textContent=`${index+1}/${scenes.length}`;q('.nbp-progress i',panel).style.width=`${((index+1)/scenes.length)*100}%`;q('[data-nbp-prev]',panel).disabled=index===0;q('[data-nbp-next]',panel).disabled=index===scenes.length-1;q('[data-nbp-play]',panel).textContent=playing?'Pause':'Play'}
async function go(i,expected=null){if(!map)return;index=Math.max(0,Math.min(scenes.length-1,i));render();const s=scenes[index];proposal(s.proposal,s.year);status(`Presentation · ${s.title}`);await sleep(100);if(expected!==null&&expected!==token)return;await move(s.cam)}
function open(){ensureUI();if(!panel||!map)return;panel.hidden=false;document.documentElement.classList.add('nb-presentation-active');index=0;render();go(0)}
function close(){stop();if(panel)panel.hidden=true;document.documentElement.classList.remove('nb-presentation-active');status('Presentation closed · interactive inspection available')}
function stop(){token++;playing=false;render();try{map?.stop?.()}catch(_){}}
async function play(){if(playing||!map)return;playing=true;const t=++token;render();for(let i=index;i<scenes.length;i++){if(t!==token)return;await go(i,t);if(t!==token)return;await sleep(reduced()?200:1100)}if(t===token){playing=false;render();status('Presentation complete · Year 25 · 3,000 dwelling units represented')}}
function maybeAutoOpen(){if(autoOpened||!AUTO||!map||!panel)return;autoOpened=true;setTimeout(()=>{open();setTimeout(()=>play(),450)},450)}
function discover(){ensureUI();const m=window.__northBarnesMap;if(m&&m!==map)map=m;maybeAutoOpen();if(!watch)watch=setInterval(()=>{ensureUI();const n=window.__northBarnesMap;if(n&&n!==map)map=n;maybeAutoOpen()},500)}
document.addEventListener('keydown',e=>{if(panel?.hidden)return;if(e.key==='Escape'){e.preventDefault();close()}else if(e.key==='ArrowRight'){e.preventDefault();stop();go(index+1)}else if(e.key==='ArrowLeft'){e.preventDefault();stop();go(index-1)}else if(e.key===' '){e.preventDefault();playing?stop():play()}});
window.NorthBarnesPresentation={version:V,open,close,play,stop,go,state:()=>({open:!!panel&&!panel.hidden,index,playing,scene:scenes[index]?.k,auto:AUTO})};discover();addEventListener('pagehide',()=>{if(watch)clearInterval(watch);stop()},{once:true});
})();
