(()=>{
const V='32.0',SRC='north-barnes-v32',LIMIT={5:2,10:3,15:4,20:5,25:7},TARGET={1:350,2:350,3:700,4:700,5:550,6:175,7:175};
const OLD=['v28-parks','v28-water','v28-parking','v28-road-casing','v28-roads','v28-paths','v28-homes','v28-roofs','v28-facilities','v28-trees','v30-green','v30-water','v30-road-casing','v30-roads','v30-homes','v30-roofs','v30-trees'];
const L=['v32-groundworks','v32-haul-casing','v32-haul','v32-green','v32-water','v32-road-casing','v32-roads','v32-homes','v32-roofs','v32-trees'];
let map=null,installed=false,visible=false,year=25,lastV,lastY,summary=null,stats={};
const q=(s,r=document)=>r.querySelector(s);
function hash(s){let h=2166136261>>>0;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rng(a){return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function box(r){const x=r.map(p=>p[0]),y=r.map(p=>p[1]);return[Math.min(...x),Math.min(...y),Math.max(...x),Math.max(...y)]}
function inside(p,ring){let c=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const a=ring[i],b=ring[j];if(((a[1]>p[1])!=(b[1]>p[1]))&&(p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0]))c=!c}return c}
function rotate(cx,cy,pts,a=0){a*=Math.PI/180;const ca=Math.cos(a),sa=Math.sin(a),p=pts.map(([x,y])=>[cx+x*ca-y*sa,cy+x*sa+y*ca]);p.push(p[0]);return p}
function footprint(cx,cy,w,h,a,typ,R){let pts;if(typ==='courtyard')pts=[[-.5,-.5],[.5,-.5],[.5,.5],[.16,.5],[.16,.08],[-.16,.08],[-.16,.5],[-.5,.5]].map(([x,y])=>[x*w,y*h]);
 else if(typ==='terrace')pts=[[-.5,-.42],[.5,-.42],[.5,.42],[.14,.42],[.14,.28],[-.08,.28],[-.08,.42],[-.5,.42]].map(([x,y])=>[x*w,y*h]);
 else if(typ==='apartment')pts=[[-.5,-.36],[-.18,-.5],[.32,-.47],[.5,-.08],[.42,.42],[.08,.5],[-.4,.35],[-.5,.02]].map(([x,y])=>[x*w,y*h]);
 else if(typ==='semi-detached')pts=[[-.5,-.5],[.5,-.5],[.5,.18],[.2,.18],[.2,.5],[-.5,.5]].map(([x,y])=>[x*w,y*h]);
 else pts=[[-.5,-.45],[.34,-.5],[.5,-.12],[.42,.44],[-.08,.5],[-.5,.24]].map(([x,y])=>[x*w,y*h]);
 const jitter=Math.min(w,h)*.045;pts=pts.map(([x,y],i)=>[x+(R()-.5)*jitter*(i%2?1:.5),y+(R()-.5)*jitter]);return rotate(cx,cy,pts,a)}
function ellipse(cx,cy,rx,ry,n=28,j=.08,R=null){const p=[];for(let i=0;i<n;i++){const a=2*Math.PI*i/n,s=R?1+(R()-.5)*j:1;p.push([cx+Math.cos(a)*rx*s,cy+Math.sin(a)*ry*s])}p.push(p[0]);return p}
function F(kind,phase,geometry,p={}){return{type:'Feature',properties:{kind,phase,geometry_status:'illustrative',...p},geometry}}
function phaseFor(t){if(t<.13)return 1;if(t<.25)return 2;if(t<.46)return 3;if(t<.68)return 4;if(t<.86)return 5;if(t<.93)return 6;return 7}
function build(base){const env=base.features.find(f=>f?.properties?.kind==='site-envelope');if(!env)throw Error('site-envelope missing');const ring=env.geometry.coordinates[0];const [x0,y0,x1,y1]=box(ring),dx=x1-x0,dy=y1-y0,R=rng(hash('north-barnes-v32'));const out=[],used={1:0,2:0,3:0,4:0,5:0,6:0,7:0};stats={buildings:0,dwellings:0,roads:0,parks:0,trees:0,groundworks:0};
 const spine=[];for(let i=0;i<48;i++){const t=i/47;const x=x0+dx*(.08+.84*t),y=y0+dy*(.20+.58*t+.07*Math.sin(t*Math.PI*2.15));spine.push([x,y])}out.push(F('road',1,{type:'LineString',coordinates:spine},{road_class:'primary'}));stats.roads++;
 const branchSeeds=[];for(let b=0;b<14;b++){const t=.055+b*.067;const cx=x0+dx*(.11+.78*t),cy=y0+dy*(.21+.57*t+.07*Math.sin(t*Math.PI*2.15)),ang=(-66+132*((b%7)/6))+(R()-.5)*16;const len=dy*(.12+.11*R()),a=ang*Math.PI/180,pts=[];for(let i=0;i<11;i++){const u=(i/10-.5)*2,xx=cx+Math.cos(a)*len*u,yy=cy+Math.sin(a)*len*u+dy*.015*Math.sin(i*.8+b);if(inside([xx,yy],ring))pts.push([xx,yy])}if(pts.length>2){const ph=phaseFor(t);out.push(F('road',ph,{type:'LineString',coordinates:pts},{road_class:b%4===0?'secondary':'local'}));branchSeeds.push({cx,cy,ph,t});stats.roads++}}
 const greens=[[.19,.31,.075,.055],[.42,.49,.09,.06],[.68,.67,.09,.06],[.61,.29,.06,.045],[.30,.73,.06,.045],[.81,.48,.045,.035]];greens.forEach((g,i)=>{const [xf,yf,rx,ry]=g,cx=x0+dx*xf,cy=y0+dy*yf;if(inside([cx,cy],ring)){out.push(F('green',Math.min(7,1+i),{type:'Polygon',coordinates:[ellipse(cx,cy,dx*rx,dy*ry,30,.12,R)]},{use:'open-space'}));stats.parks++}});out.push(F('water',2,{type:'Polygon',coordinates:[ellipse(x0+dx*.18,y0+dy*.30,dx*.028,dy*.020,26,.16,R)]},{use:'attenuation-drainage'}));
 const works=[[.15,.23,.105,.07,1],[.31,.37,.115,.075,2],[.49,.50,.12,.08,3],[.66,.64,.115,.075,4],[.79,.75,.095,.065,5]];for(const [xf,yf,rx,ry,ph] of works){const cx=x0+dx*xf,cy=y0+dy*yf;if(!inside([cx,cy],ring))continue;out.push(F('groundwork',ph,{type:'Polygon',coordinates:[ellipse(cx,cy,dx*rx,dy*ry,24,.20,R)]},{use:'enabling-earthworks',temporary:true}));stats.groundworks++}
 const haul=[];for(let i=0;i<26;i++){const t=i/25,x=x0+dx*(.07+.86*t),y=y0+dy*(.17+.61*t+.085*Math.sin(t*Math.PI*2));if(inside([x,y],ring))haul.push([x,y])}if(haul.length>2)out.push(F('haul',1,{type:'LineString',coordinates:haul},{use:'temporary-haul-route',temporary:true}));
 const candidates=[];for(let r=0;r<40;r++)for(let c=0;c<34;c++){const xf=(c+.5)/34,yf=(r+.5)/40,x=x0+dx*xf+(R()-.5)*dx*.010,y=y0+dy*yf+(R()-.5)*dy*.010;if(!inside([x,y],ring))continue;const t=(xf*.60+yf*.40),sy=.20+.58*xf+.07*Math.sin(xf*Math.PI*2.15);if(Math.abs(yf-sy)<.030)continue;if(greens.some(([gx,gy,rx,ry])=>(((xf-gx)/rx)**2+((yf-gy)/ry)**2)<1.30))continue;candidates.push({x,y,xf,yf,t,score:R()})}candidates.sort((a,b)=>a.t-b.t||a.score-b.score);
 let remaining=3000;for(const c of candidates){if(remaining<=0)break;const ph=phaseFor(c.t);if(used[ph]>=(TARGET[ph]||0))continue;const room=(TARGET[ph]||0)-used[ph],uPick=c.t>.72?[8,12,4,2]:c.t>.38?[4,4,2,8,1]:[1,2,2,4,1];let units=Math.min(room,remaining,uPick[Math.floor(R()*uPick.length)]);if(units<=0)continue;let typ=units>=10?'apartment':units>=6?'courtyard':units>=4?'terrace':units===2?'semi-detached':'detached';const angle=(Math.atan2(.58+.07*Math.PI*2.15*Math.cos(c.xf*Math.PI*2.15),.84)*180/Math.PI)+(R()-.5)*32;const w=dx*(typ==='apartment'?.014:typ==='courtyard'?.012:typ==='terrace'?.010:.0072),h=dy*(typ==='apartment'?.013:typ==='courtyard'?.011:typ==='terrace'?.0085:.0068),storeys=typ==='apartment'?4:typ==='courtyard'?3:2,height=storeys*2.8+(R()-.5)*.6;const p={use:'residential',typology:typ,dwelling_units:units,storeys,height_m:height,evidence_status:'primary-supported-maximum-only'};const home=footprint(c.x,c.y,w,h,angle,typ,R),roof=footprint(c.x,c.y,w*.84,h*.84,angle,typ,R);out.push(F('home',ph,{type:'Polygon',coordinates:[home]},p),F('roof',ph,{type:'Polygon',coordinates:[roof]},{...p,base_m:height,roof_m:height+(typ==='apartment'?.8:1.25)}));used[ph]+=units;remaining-=units;stats.buildings++;stats.dwellings+=units}
 if(remaining!==0)throw Error('v32 dwelling allocation '+remaining);
 for(let i=0;i<360;i++){const t=i/359,x=x0+dx*(.06+.88*((t*1.73)%1)),y=y0+dy*(.08+.84*((t*2.37)%1));if(inside([x,y],ring)){out.push(F('tree',phaseFor((x-x0)/dx),{type:'Point',coordinates:[x,y]},{use:'landscape-structure'}));stats.trees++}}
 return{type:'FeatureCollection',metadata:{version:V,status:'field-led-organic-illustrative-settlement',not_for_planning_use:true,generated_dwelling_units:stats.dwellings,groundworks:'illustrative-enabling-works'},features:out}}
function add(s,before){try{if(!map.getLayer(s.id))map.addLayer(s,before)}catch(e){console.warn('v32 layer',s.id,e)}}
function hideOld(){for(const id of OLD)try{if(map.getLayer(id))map.setLayoutProperty(id,'visibility','none')}catch(_){}}
function show(on){for(const id of L)try{if(map.getLayer(id))map.setLayoutProperty(id,'visibility',on?'visible':'none')}catch(_){}if(on)hideOld()}
function phase(){const lim=LIMIT[year]||7;for(const id of L)try{if(map.getLayer(id))map.setFilter(id,['<=',['get','phase'],lim])}catch(_){}}
function ui(){if(summary?.isConnected)return;const host=q('#immersive-experience');if(!host)return;summary=document.createElement('div');summary.id='nb-v32-summary';summary.style.cssText='position:absolute;z-index:6;left:16px;bottom:68px;max-width:min(720px,calc(100% - 32px));padding:8px 11px;border:1px solid #ffffff35;border-radius:12px;background:#07110ddd;color:#fff;font:700 .72rem/1.25 system-ui;backdrop-filter:blur(10px);pointer-events:none';host.appendChild(summary)}
function update(){ui();if(!summary)return;summary.hidden=!visible||document.documentElement.classList.contains('nb-presentation-active');summary.innerHTML='<b style="color:#f3d37a">v32 field-led visual scenario</b> · Year '+year+' · '+stats.dwellings.toLocaleString('en-GB')+' dwellings site-wide · organic footprints + enabling works · illustrative, not an official masterplan'}
async function install(){if(installed||!map||!map.isStyleLoaded?.())return;const r=await fetch('data/proposal-preview.geojson?v=22',{cache:'no-store'});if(!r.ok)return;const data=build(await r.json());window.__northBarnesSettlementV32=data;if(!map.getSource(SRC))map.addSource(SRC,{type:'geojson',data});
 add({id:'v32-groundworks',type:'fill',source:SRC,filter:['==',['get','kind'],'groundwork'],layout:{visibility:'none'},paint:{'fill-color':'#8d6b4b','fill-opacity':.48,'fill-outline-color':'#6e5137'}});
 add({id:'v32-green',type:'fill',source:SRC,filter:['==',['get','kind'],'green'],layout:{visibility:'none'},paint:{'fill-color':'#6e915c','fill-opacity':.62}});
 add({id:'v32-water',type:'fill',source:SRC,filter:['==',['get','kind'],'water'],layout:{visibility:'none'},paint:{'fill-color':'#75a9b8','fill-opacity':.75}});
 add({id:'v32-haul-casing',type:'line',source:SRC,filter:['==',['get','kind'],'haul'],layout:{visibility:'none','line-cap':'round','line-join':'round'},paint:{'line-color':'#5b4635','line-width':['interpolate',['linear'],['zoom'],11,1.2,15,8,17,12]}});
 add({id:'v32-haul',type:'line',source:SRC,filter:['==',['get','kind'],'haul'],layout:{visibility:'none','line-cap':'round','line-join':'round'},paint:{'line-color':'#b99b75','line-width':['interpolate',['linear'],['zoom'],11,.7,15,4.8,17,7.5],'line-dasharray':[2,1.3]}});
 add({id:'v32-road-casing',type:'line',source:SRC,filter:['==',['get','kind'],'road'],layout:{visibility:'none','line-cap':'round','line-join':'round'},paint:{'line-color':'#353a37','line-width':['interpolate',['linear'],['zoom'],11,1.4,15,10,17,16]}});
 add({id:'v32-roads',type:'line',source:SRC,filter:['==',['get','kind'],'road'],layout:{visibility:'none','line-cap':'round','line-join':'round'},paint:{'line-color':['match',['get','road_class'],'primary','#d7d2c5','secondary','#c5c2b8','#b7b5ad'],'line-width':['interpolate',['linear'],['zoom'],11,.9,15,6.4,17,10]}});
 add({id:'v32-homes',type:'fill-extrusion',source:SRC,filter:['==',['get','kind'],'home'],minzoom:11.5,layout:{visibility:'none'},paint:{'fill-extrusion-color':['match',['get','typology'],'apartment','#a57f69','courtyard','#ad8c72','terrace','#c09b7d','semi-detached','#ceb08e','#d8b995'],'fill-extrusion-height':['get','height_m'],'fill-extrusion-opacity':.93}});
 add({id:'v32-roofs',type:'fill-extrusion',source:SRC,filter:['==',['get','kind'],'roof'],minzoom:12.7,layout:{visibility:'none'},paint:{'fill-extrusion-color':'#765747','fill-extrusion-base':['get','base_m'],'fill-extrusion-height':['get','roof_m'],'fill-extrusion-opacity':.96}});
 add({id:'v32-trees',type:'circle',source:SRC,filter:['==',['get','kind'],'tree'],minzoom:12.7,layout:{visibility:'none'},paint:{'circle-radius':['interpolate',['linear'],['zoom'],13,1.5,16,4.8],'circle-color':'#426844','circle-stroke-color':'#2a4a31','circle-stroke-width':.5}});
 installed=true;sync(true)}
function sync(force=false){const p=window.NorthBarnesProposal?.state?.();if(!p)return;visible=!!p.visible;year=[5,10,15,20,25].includes(+p.year)?+p.year:25;if(!installed){install().catch(console.error);return}if(force||visible!==lastV){show(visible);lastV=visible}if(force||year!==lastY){phase();lastY=year}if(visible)hideOld();update()}
function discover(){const m=window.__northBarnesMap;if(m&&m!==map){map=m;installed=false;setTimeout(()=>install().catch(console.error),250)}}
const api={version:V,state:()=>({installed,visible,year,stats:{...stats},data:window.__northBarnesSettlementV32})};window.NorthBarnesV32=api;window.NorthBarnesV30=api;discover();const a=setInterval(()=>{discover();sync()},700);addEventListener('pagehide',()=>clearInterval(a),{once:true});
})();
