(()=>{
const V='30.0',SRC='north-barnes-v30',LIMIT={5:2,10:3,15:4,20:5,25:7},TARGET={1:350,2:350,3:700,4:700,5:550,6:175,7:175};
const OLD=['v28-parks','v28-water','v28-parking','v28-road-casing','v28-roads','v28-paths','v28-homes','v28-roofs','v28-facilities','v28-trees'];
const L=['v30-green','v30-water','v30-road-casing','v30-roads','v30-homes','v30-roofs','v30-trees'];
let map=null,installed=false,visible=false,year=25,lastV,lastY,summary=null,stats={};
const q=(s,r=document)=>r.querySelector(s);
function hash(s){let h=2166136261>>>0;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rng(a){return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function box(r){const x=r.map(p=>p[0]),y=r.map(p=>p[1]);return[Math.min(...x),Math.min(...y),Math.max(...x),Math.max(...y)]}
function inside(p,ring){let c=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const a=ring[i],b=ring[j];if(((a[1]>p[1])!=(b[1]>p[1]))&&(p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0]))c=!c}return c}
function rect(cx,cy,w,h,a=0){a*=Math.PI/180;const ca=Math.cos(a),sa=Math.sin(a),p=[[-w/2,-h/2],[w/2,-h/2],[w/2,h/2],[-w/2,h/2]].map(([x,y])=>[cx+x*ca-y*sa,cy+x*sa+y*ca]);p.push(p[0]);return p}
function ellipse(cx,cy,rx,ry,n=28){const p=[];for(let i=0;i<n;i++){const a=2*Math.PI*i/n;p.push([cx+Math.cos(a)*rx,cy+Math.sin(a)*ry])}p.push(p[0]);return p}
function F(kind,phase,geometry,p={}){return{type:'Feature',properties:{kind,phase,geometry_status:'illustrative',...p},geometry}}
function phaseFor(t){if(t<.13)return 1;if(t<.25)return 2;if(t<.46)return 3;if(t<.68)return 4;if(t<.86)return 5;if(t<.93)return 6;return 7}
function build(base){const env=base.features.find(f=>f?.properties?.kind==='site-envelope');const ring=env.geometry.coordinates[0];const [x0,y0,x1,y1]=box(ring),dx=x1-x0,dy=y1-y0,R=rng(hash('north-barnes-v30'));const out=[],used={1:0,2:0,3:0,4:0,5:0,6:0,7:0};stats={buildings:0,dwellings:0,roads:0,parks:0,trees:0};
 const spine=[];for(let i=0;i<42;i++){const t=i/41;const x=x0+dx*(.10+.80*t),y=y0+dy*(.22+.56*t+.065*Math.sin(t*Math.PI*2.2));spine.push([x,y])}out.push(F('road',1,{type:'LineString',coordinates:spine},{road_class:'primary'}));stats.roads++;
 for(let b=0;b<11;b++){const t=.08+b*.084;const cx=x0+dx*(.12+.76*t),cy=y0+dy*(.23+.55*t+.065*Math.sin(t*Math.PI*2.2)),ang=(-58+116*((b%5)/4))+R()*10;const len=dy*(.16+.08*R()),a=ang*Math.PI/180,pts=[];for(let i=0;i<9;i++){const u=(i/8-.5)*2,xx=cx+Math.cos(a)*len*u,yy=cy+Math.sin(a)*len*u+dy*.012*Math.sin(i*.9+b);if(inside([xx,yy],ring))pts.push([xx,yy])}if(pts.length>2){out.push(F('road',phaseFor(t),{type:'LineString',coordinates:pts},{road_class:b%3===0?'secondary':'local'}));stats.roads++}}
 const greens=[[.22,.33,.08,.06],[.48,.51,.09,.065],[.72,.70,.085,.055],[.57,.27,.055,.04],[.31,.74,.055,.04]];greens.forEach((g,i)=>{const [xf,yf,rx,ry]=g,cx=x0+dx*xf,cy=y0+dy*yf;if(inside([cx,cy],ring)){out.push(F('green',Math.min(7,1+i),{type:'Polygon',coordinates:[ellipse(cx,cy,dx*rx,dy*ry)]},{use:'open-space'}));stats.parks++}});out.push(F('water',2,{type:'Polygon',coordinates:[ellipse(x0+dx*.18,y0+dy*.31,dx*.025,dy*.018)]},{use:'attenuation-drainage'}));
 const candidates=[];for(let r=0;r<35;r++)for(let c=0;c<28;c++){const xf=(c+.5)/28,yf=(r+.5)/35,x=x0+dx*xf+(R()-.5)*dx*.008,y=y0+dy*yf+(R()-.5)*dy*.008;if(!inside([x,y],ring))continue;const t=(xf*.60+yf*.40);const sy=.22+.56*xf+.065*Math.sin(xf*Math.PI*2.2);if(Math.abs(yf-sy)<.035)continue;if(greens.some(([gx,gy,rx,ry])=>(((xf-gx)/rx)**2+((yf-gy)/ry)**2)<1.35))continue;candidates.push({x,y,xf,yf,t,score:R()})}candidates.sort((a,b)=>a.t-b.t||a.score-b.score);
 let remaining=3000;for(const c of candidates){if(remaining<=0)break;const ph=phaseFor(c.t);if(used[ph]>=(TARGET[ph]||0))continue;const room=(TARGET[ph]||0)-used[ph];const uPick=c.t>.72?[8,12,4,2]:c.t>.38?[4,4,2,8,1]:[1,2,2,4,1];let units=Math.min(room,remaining,uPick[Math.floor(R()*uPick.length)]);if(units<=0)continue;let typ=units>=10?'apartment':units>=6?'courtyard':units>=4?'terrace':units===2?'semi-detached':'detached';const angle=(Math.atan2(.56+.065*Math.PI*2.2*Math.cos(c.xf*Math.PI*2.2),.80)*180/Math.PI)+(R()-.5)*22;const w=dx*(typ==='apartment'?.012:typ==='courtyard'?.010:typ==='terrace'?.008:.0065),h=dy*(typ==='apartment'?.012:typ==='courtyard'?.010:typ==='terrace'?.0075:.006),storeys=typ==='apartment'?4:typ==='courtyard'?3:2,height=storeys*2.8+(R()-.5)*.5;const p={use:'residential',typology:typ,dwelling_units:units,storeys,height_m:height,evidence_status:'primary-supported-maximum-only'};out.push(F('home',ph,{type:'Polygon',coordinates:[rect(c.x,c.y,w,h,angle)]},p),F('roof',ph,{type:'Polygon',coordinates:[rect(c.x,c.y,w*.84,h*.84,angle)]},{...p,base_m:height,roof_m:height+(typ==='apartment'?.8:1.25)}));used[ph]+=units;remaining-=units;stats.buildings++;stats.dwellings+=units}
 if(remaining!==0)throw Error('v30 dwelling allocation '+remaining);
 for(let i=0;i<260;i++){const t=i/259,x=x0+dx*(.08+.84*((t*1.73)%1)),y=y0+dy*(.10+.80*((t*2.37)%1));if(inside([x,y],ring)){out.push(F('tree',phaseFor((x-x0)/dx),{type:'Point',coordinates:[x,y]},{use:'landscape-structure'}));stats.trees++}}
 return{type:'FeatureCollection',metadata:{version:V,status:'continuous-road-led-illustrative-settlement',not_for_planning_use:true,generated_dwelling_units:stats.dwellings},features:out}}
function add(s){try{if(!map.getLayer(s.id))map.addLayer(s)}catch(e){console.warn('v30 layer',s.id,e)}}
function hideOld(){for(const id of OLD)try{if(map.getLayer(id))map.setLayoutProperty(id,'visibility','none')}catch(_){}}
function show(on){for(const id of L)try{if(map.getLayer(id))map.setLayoutProperty(id,'visibility',on?'visible':'none')}catch(_){}if(on)hideOld()}
function phase(){const lim=LIMIT[year]||7;for(const id of L)try{if(map.getLayer(id))map.setFilter(id,['<=',['get','phase'],lim])}catch(_){}}
function ui(){if(summary?.isConnected)return;const host=q('#immersive-experience');if(!host)return;summary=document.createElement('div');summary.id='nb-v30-summary';summary.style.cssText='position:absolute;z-index:6;left:16px;bottom:68px;max-width:min(650px,calc(100% - 32px));padding:8px 11px;border:1px solid #ffffff35;border-radius:12px;background:#07110ddd;color:#fff;font:700 .72rem/1.25 system-ui;backdrop-filter:blur(10px);pointer-events:none';host.appendChild(summary)}
function update(){ui();if(!summary)return;summary.hidden=!visible||document.documentElement.classList.contains('nb-presentation-active');summary.innerHTML='<b style="color:#f3d37a">v30 continuous settlement scenario</b> · Year '+year+' · '+stats.dwellings.toLocaleString('en-GB')+' dwellings site-wide · road-led morphology · illustrative, not an official masterplan'}
async function install(){if(installed||!map||!map.isStyleLoaded?.())return;const r=await fetch('data/proposal-preview.geojson?v=22',{cache:'no-store'});if(!r.ok)return;const data=build(await r.json());window.__northBarnesSettlementV30=data;if(!map.getSource(SRC))map.addSource(SRC,{type:'geojson',data});add({id:'v30-green',type:'fill',source:SRC,filter:['==',['get','kind'],'green'],layout:{visibility:'none'},paint:{'fill-color':'#6e915c','fill-opacity':.62}});add({id:'v30-water',type:'fill',source:SRC,filter:['==',['get','kind'],'water'],layout:{visibility:'none'},paint:{'fill-color':'#75a9b8','fill-opacity':.75}});add({id:'v30-road-casing',type:'line',source:SRC,filter:['==',['get','kind'],'road'],layout:{visibility:'none','line-cap':'round','line-join':'round'},paint:{'line-color':'#353a37','line-width':['interpolate',['linear'],['zoom'],11,1.4,15,10,17,16]}});add({id:'v30-roads',type:'line',source:SRC,filter:['==',['get','kind'],'road'],layout:{visibility:'none','line-cap':'round','line-join':'round'},paint:{'line-color':['match',['get','road_class'],'primary','#d7d2c5','secondary','#c5c2b8','#b7b5ad'],'line-width':['interpolate',['linear'],['zoom'],11,.9,15,6.4,17,10]}});add({id:'v30-homes',type:'fill-extrusion',source:SRC,filter:['==',['get','kind'],'home'],minzoom:11.5,layout:{visibility:'none'},paint:{'fill-extrusion-color':['match',['get','typology'],'apartment','#a57f69','courtyard','#ad8c72','terrace','#c09b7d','semi-detached','#ceb08e','#d8b995'],'fill-extrusion-height':['get','height_m'],'fill-extrusion-opacity':.93}});add({id:'v30-roofs',type:'fill-extrusion',source:SRC,filter:['==',['get','kind'],'roof'],minzoom:12.7,layout:{visibility:'none'},paint:{'fill-extrusion-color':'#765747','fill-extrusion-base':['get','base_m'],'fill-extrusion-height':['get','roof_m'],'fill-extrusion-opacity':.96}});add({id:'v30-trees',type:'circle',source:SRC,filter:['==',['get','kind'],'tree'],minzoom:12.7,layout:{visibility:'none'},paint:{'circle-radius':['interpolate',['linear'],['zoom'],13,1.5,16,4.8],'circle-color':'#426844','circle-stroke-color':'#2a4a31','circle-stroke-width':.5}});installed=true;sync(true)}
function sync(force=false){const p=window.NorthBarnesProposal?.state?.();if(!p)return;visible=!!p.visible;year=[5,10,15,20,25].includes(+p.year)?+p.year:25;if(!installed){install().catch(console.error);return}if(force||visible!==lastV){show(visible);lastV=visible}if(force||year!==lastY){phase();lastY=year}if(visible)hideOld();update()}
function discover(){const m=window.__northBarnesMap;if(m&&m!==map){map=m;installed=false;setTimeout(()=>install().catch(console.error),250)}}
window.NorthBarnesV30={version:V,state:()=>({installed,visible,year,stats:{...stats},data:window.__northBarnesSettlementV30})};discover();const a=setInterval(()=>{discover();sync()},700);addEventListener('pagehide',()=>clearInterval(a),{once:true});
})();
